### ISSUE TITLE
Final color scheme

### ISSUE THREAD

**Issue by Raquel-Costa** [ulynks/www#10]
- Final colors
- Use the colors defined on the color styles
- Style guide updated

**Comment by luzep** [comment]
Worked on color consistency and contrasts.
Agreed on a color scheme for the time being and updated the style guide based on functionalities, i.e.

<img width="387" alt="Screenshot 2024-01-10 at 11 03 40" src="https://github.com/ulynks/www/assets/52827445/015718ec-f022-4873-977e-82495c11a0ed">
